---
# tasks - install_el8.yml for nerve4-aide

- name: Install aide on RHEL8 based hosts
  ansible.builtin.dnf: 
    name: "aide"
    state: present

- name: Initialize AIDE
  become: true
  ansible.builtin.command: 
    cmd: /usr/sbin/aide --init