---
# tasks - main.yml for nerve4-aide

- include_tasks: install_el7.yml
  when: 
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "7"

- include_tasks: install_el8.yml
  when: 
    (ansible_distribution == "RedHat" and ansible_distribution_major_version == "8") or
    (ansible_distribution in "Rocky")

- include_tasks: install_ubuntu.yml
  when: 
    - ansible_distribution == "Ubuntu"

- include_tasks: configure_aide.yml